version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: balance-api
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: balance-db